### ISSUE TITLE
docs profile for edown

### ISSUE THREAD

**Issue by tsloughter** [barrel-db/erlang-lru#1]
I noticed you use `dev` profile for including edown. The `edoc` provider runs under the `docs` profile, so easier if you put doc specific stuff like edown under that profile, then you won't need `as dev`, just `rebar3 edoc`.

**Comment by benoitc** [comment]
oh nice! I mostly copied the code from hackney. i am doing the change now.

**Comment by benoitc** [comment]
done. Thanks!
